import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Navbar from "@/components/Navbar";
import Featured from "@/components/Featured";
import Carousel from "@/components/Carousel";
import Choose from "@/components/Choose";
import Partners from "@/components/Partners";
import Footer from "@/components/Footer";
import FoodMenu from "@/components/FoodMenu";
import FoodMember from "@/components/FoodMember";
import Testimonials from "@/components/Testimonials";
import About from "@/components/About";
import Blog from "@/components/Blog";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Foodtuck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <Navbar />
        <Featured />
        <About />
      </div>
      <div className={styles.carousel}>
        <Carousel />
      </div>
      <div className={styles.other}>
        <Choose />
        <FoodMenu />
      </div>
      <FoodMember />

      <div className={styles.other}>
        <Testimonials />
        <Blog />
        <Partners />
      </div>
      <Contact />
      <Footer />
    </>
  );
}
